:sparkles: 为unitofwork/manager 增加async 功能  支持 core3.1及以上版本
dotnetcore/FreeSql pull request #1220
Opened 2022-08-22 16:10 UTC by luoyunchong

2022-08-22 17:28 UTC, 2881099 commented
暂时保留更改意见，比如 BeginAsync 那里在 AOP 动态代理处理起来会比较麻烦，最终还是转嫁到我们回答问题。

2024-06-23 09:08 UTC, hyzx86 commented
> 暂时保留更改意见，比如 BeginAsync 那里在 AOP 动态代理处理起来会比较麻烦，最终还是转嫁到我们回答问题。

直接备注到XML 方法上 或者使用 特性标注增加提醒？

2024-06-23 09:09 UTC, hyzx86 requested changes

2024-06-23 09:09 UTC, hyzx86 commented on FreeSql.DbContext/UnitOfWork/UnitOfWork.cs
> +#if NETCOREAPP3_1_OR_GREATER
```suggestion
#if NETCOREAPP3_1_OR_GREATER
[Obsolete("实验功能，在 AOP 动态代理处理起来会比较麻烦，https://github.com/dotnetcore/FreeSql/pull/1220")]
```

2024-06-23 09:11 UTC, hyzx86 requested changes

2024-06-23 09:11 UTC, hyzx86 commented on FreeSql.DbContext/UnitOfWork/UnitOfWork.cs
> +        public async Task<DbTransaction> GetOrBeginTransactionAsync(bool isCreate = true, CancellationToken cancellationToken = default)
```suggestion
        [Obsolete("实验功能，在 AOP 动态代理处理起来会比较麻烦，https://github.com/dotnetcore/FreeSql/pull/1220")]
        public async Task<DbTransaction> GetOrBeginTransactionAsync(bool isCreate = true, CancellationToken cancellationToken = default)
```

2026-04-14 03:20 UTC, closed without merging